---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-12.04
    driver:
      box: express42/ubuntu12.04-chef11
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[zabbix_lwrp_test]
    attributes:
