---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu-upstart:14.04
      disable_upstart: false
      run_command: '/sbin/init'
      provision_command:
#       Source for snmp-mibs-downloader package
        - echo 'deb http://archive.ubuntu.com/ubuntu trusty multiverse' >> /etc/apt/sources.list
#       Netstat for Inspec
        - apt-get update && apt-get install -y net-tools


  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      run_command: '/sbin/init'
      provision_command:
#       For systemd
        - systemctl set-default multi-user.target
#       Netstat for Inspec
        - apt-get install -y net-tools

  - name: centos-7
    driver_config:
      image: centos:7
      run_command: '/usr/sbin/init'
      provision_command:
#       Install package's docs
#       For zabbix init db sql files
        - sed -i 's/^tsflags/#tsflags/' /etc/yum.conf
#       For nginx package
        - yum -y install openssl openssl-devel
#       Netstat for Inspec
        - yum -y install net-tools

verifier:
  name: inspec

suites:
  - name: zabbix24
    run_list:
      - recipe[zabbix_lwrp_test::zabbix24]
    excludes:
      - ubuntu-16.04
    verifier:
      inspec_tests:
        - path: test/integration/zabbix_lwrp_test

  - name: zabbix30
    run_list:
      - recipe[zabbix_lwrp_test::zabbix30]
    verifier:
      inspec_tests:
        - path: test/integration/zabbix_lwrp_test

  - name: zabbix32
    run_list:
      - recipe[zabbix_lwrp_test::zabbix32]
    verifier:
      inspec_tests:
        - path: test/integration/zabbix_lwrp_test
