Lint/AssignmentInCondition:
  Enabled: false
Lint/LiteralInCondition:
  Enabled: false
Metrics/AbcSize:
  Max: 66
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/LineLength:
  Max: 203
Metrics/MethodLength:
  Max: 80
Metrics/PerceivedComplexity:
  Max: 10
Style/EachWithObject:
  Enabled: false
Style/Next:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
